name: Build and deploy Node.js app to Azure Web App - reelrush

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload source files only
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./
            !node_modules/
            !node_modules.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Install production dependencies
        run: npm ci

      - name: Verify Next.js binary exists
        run: ls node_modules/.bin/next

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reelrush'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DF0D798318DB42A1996807327B339CDB }}
